In [ ]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


In [ ]:
#3. Create a null vector of size 10 
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#4.How to find the memory size of any array
print(x.size)
print(x.itemsize)
print(x.nbytes)


10
8
80


In [ ]:
#5. How to get the documentation of the numpy add function from the command line? (★☆☆)
#(hint: np.info)
print(np.info(np.add))

None


In [ ]:
#6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
#(hint: array[4])
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
#Create a vector with values ranging from 10 to 49 (★☆☆)
#(hint: np.arange)

y = np.arange(10,49)
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [ ]:
#8. Reverse a vector (first element becomes last) (★☆☆)
#(hint: array[::-1])
y = np.arange(10,49)
y1=y[::-1]
y1



array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [ ]:
#9.Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
#(hint: reshape)
z = np.arange(0,9)
w = z.reshape(3,3)
w


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0]
#(hint: np.nonzero)
x = [1,2,0,0,4,0]
np.nonzero(x)

(array([0, 1, 4]),)

In [ ]:
#11. Create a 3x3 identity matrix 
#(hint: np.eye)
w = np.eye(3)
w

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#12. Create a 3x3x3 array with random values 
#(hint: np.random.random)
x = np.random.randn(3,3,3)
x

array([[[-1.6490123 , -0.87571325,  1.20825984],
        [-0.07871069, -2.05238792, -0.42825055],
        [-1.46962304,  0.34522029, -1.49041684]],

       [[ 1.65607048, -1.28395842,  0.07129066],
        [ 0.08503484,  2.07831869,  1.2109832 ],
        [ 1.45045957,  0.80092139,  1.54888663]],

       [[-1.68477287,  0.68994969, -1.16622367],
        [-0.68061923, -0.18305824,  0.35941502],
        [ 0.85465026, -0.02193239,  1.45948818]]])

In [ ]:
#13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
#(hint: min, max)
x = np.random.randn(10,10)

w = np.max(x)
w


2.0806701087532784

In [ ]:
y = np.min(x)
y

-2.3899591775006557

In [ ]:
#14. Create a random vector of size 30 and find the mean value (★☆☆)
#(hint: mean)
x = np.random.randn(30)
np.mean(x)

0.011739751670805348

In [ ]:
#15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
#(hint: array[1:-1, 1:-1])
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#16. How to add a border (filled with 0's) around an existing array? 
#(hint: np.pad)
x= np.ones((3,3))
print(x)
x = np.pad(x,pad_width = 1,mode = 'constant',constant_values = '0')
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 
x = np.diag(1+np.arange(5),k = -1)
x

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0]])

In [ ]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern 
#(hint: array[::2])
x = np.zeros((8,8))
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)



[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
#. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
#(hint: np.unravel_index)
x = np.unravel_index(100,(6,7,8))
x

(1, 5, 4)

In [ ]:
#21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
#(hint: np.tile)
x = np.array([[0,1],[1,0]])
w = np.tile(x,(4,4))
w

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
#22. Normalize a 5x5 random matrix (★☆☆)
#(hint: (x - min) / (max - min))
x = np.random.randn(5,5)
y = x - (np.min(x))
z = np.max(x)-np.min(x)
q = y/x
q

array([[  2.97047943,   2.25500657,  -0.68611094,  -0.2307605 ,
          8.72477695],
       [  2.07275023,   1.99546586,   2.59293206,   2.56400408,
         -2.59017935],
       [  3.88200669,  -0.1615853 ,  -3.04591014,  -0.52399267,
          3.43672164],
       [ 17.89828369,  -0.        , -25.20733827,  -1.09332408,
         -1.79062151],
       [ -0.52561393,  -0.30484007,   3.12903135,   1.78884512,
          1.61658729]])

In [ ]:
#Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
#(hint: np.dtype)
x = np.dtype([("r",np.ubyte),
             ("g",np.ubyte),
             ("b",np.ubyte),
             ("a",np.ubyte)])
print(x)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [ ]:
#24.Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
#(hint: np.dot | @)
x=np.dot(np.ones((5,3)), np.ones((3,2)))
x

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [ ]:
#25. Given a 1D array, negate all elements which are between 3 and 8, in place. 
#(hint: >, <=)

x = np.arange(15)
x[(x>3)&(8<=x)] *= -1
x

array([  0,   1,   2,   3,   4,   5,   6,   7,  -8,  -9, -10, -11, -12,
       -13, -14])

In [ ]:
#26. What is the output of the following script? (★☆☆)
#(hint: np.sum)
x = np.arange(5)
np.sum(x)

10

In [ ]:
#29. How to round away from zero a float array ? (★☆☆)
#(hint: np.uniform, np.copysign, np.ceil, np.abs)
x = np.random.uniform(4 ,-5, 6)
print(np.copysign(np.ceil(np.abs(x)), x))


[-1. -2.  1. -5.  2.  4.]


In [ ]:
#30. How to find common values between two arrays? (★☆☆)
#(hint: np.intersect1d)
x = np.random.randint(3,4,4)
y = np.random.randint(3,4,4)
np.intersect1d(x,y)

array([3])

In [ ]:
#31. How to ignore all numpy warnings (not recommended)? (★☆☆)
#(hint: np.seterr, np.errstate)
defaults = np.seterr(all="ignore")

_ = np.seterr(**defaults)

with np.errstate(all="ignore"):
    



In [ ]:
#33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
#(hint: np.datetime64, np.timedelta64)
today = np.datetime64('today')
yesterday = np.datetime64('today')-np.timedelta64(1)
tomaro = np.datetime64('today')+np.timedelta64(1)
print(today)
print(yesterday)
print(tomaro)

2021-09-21
2021-09-20
2021-09-22


In [ ]:
#34. How to get all the dates corresponding to the month of July 2016? (★★☆)
#(hint: np.arange(dtype=datetime64['D']))
x = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
#35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
#(hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))
a = np.ones(2)*3
b = np.ones(2)*2
np.add(a,b,out =b )
np.negative(a,out = a)
np.divide(a,2,out = a)
np.multiply(a,b,out=a)



array([-7.5, -7.5])

In [ ]:
#36. Extract the integer part of a random array using 5 different methods (★★☆) 
#(**hint**: %, np.floor, np.ceil, astype, np.trunc)
x = np.random.uniform(0,5,5)
print(x%x)
print(np.floor(x))
print(np.ceil(x))
print(x.astype(int))
print(np.floor(x))

[0. 0. 0. 0. 0.]
[2. 0. 0. 0. 1.]
[3. 1. 1. 1. 2.]
[2 0 0 0 1]
[2. 0. 0. 0. 1.]


In [ ]:
#37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
#(hint: np.arange)
x = np.zeros((5,5))
x+=np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [ ]:
#38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
#(hint: np.fromiter)
def generator():
  for x in range(10):
    yield x
x1 = np.fromiter(generator(),dtype =float,count = -1)
x1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
#hint: np.linspace)
x= np.linspace(0,1,11,endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [ ]:
#40. Create a random vector of size 10 and sort it (★★☆)
#(hint: sort)
x = np.random.randn(10)
x.sort()
x

array([-0.85389051, -0.33521354, -0.09684969,  0.0709503 ,  0.24342202,
        0.58941184,  0.61890941,  0.77320639,  0.96273638,  1.39118172])

In [ ]:
#41. How to sum a small array faster than np.sum? (★★☆)
#(hint: np.add.reduce)
x = np.arange(10)
np.add.reduce(x)

45

In [ ]:
#42. Consider two random array A and B, check if they are equal (★★☆)
#(hint: np.allclose, np.array_equal)
a = np.random.randint(2,3)
b = np.random.randint(2,3)
a1 = np.array_equal(a,b)
a1
a2 = np.allclose(a,b)
a2



True

In [ ]:
#43. Make an array immutable (read-only) (★★☆)
#(hint: flags.writeable)
x = np.zeros(5)
x.flags.writeable = False




In [ ]:
#44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
#(hint: np.sqrt, np.arctan2)
x = np.random.random((10,2))
c,d = x[:,0],x[:,1]
a = np.sqrt(c**2+d**2)
b = np.arctan2(c,d)
print(a)
print(b)

[0.81090892 0.11199056 0.72321563 0.80860428 1.10475337 0.8278803
 0.18276426 0.33698574 0.66522596 0.7543025 ]
[0.02534787 0.73298568 1.31721659 1.49261379 0.94252449 0.82160846
 1.39393531 1.56823641 1.33075188 0.64597909]


In [ ]:
#45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
#(hint: argmax)
x = np.random.randn(10)
x[x.argmax()]= 0
x


array([-0.44379821,  0.24120146, -0.06314062,  0.        ,  0.49493614,
        1.42394244,  0.40349258,  0.56300077, -0.2309812 , -0.0357515 ])

In [ ]:
#46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)
#(hint: np.meshgrid)
x = np.zeros((3,3),[('a',float),('b',float)])
x['a'],x['b'] = np.meshgrid(np.linspace(0,1,3),np.linspace(0,1,3))
x

array([[(0. , 0. ), (0.5, 0. ), (1. , 0. )],
       [(0. , 0.5), (0.5, 0.5), (1. , 0.5)],
       [(0. , 1. ), (0.5, 1. ), (1. , 1. )]],
      dtype=[('a', '<f8'), ('b', '<f8')])

In [ ]:
#47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
#(hint: np.subtract.outer)
x  = np.arange(8)
y = x +2
c = 1/ np.subtract.outer(x,y)
c



In [ ]:
#48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
#(hint: np.iinfo, np.finfo, eps)
  
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

In [ ]:
#49. How to print all the values of an array? (★★☆)
#(hint: np.set_printoptions)
import numpy as np
np.set_printoptions(threshold=np.inf)

In [ ]:
#50. How to find the closest value (to a given scalar) in a vector? (★★☆)
#hint: argmin
x = np.arange(10)
y = 5
diff =np.absolute(x-y)
z = diff.argmin()
x[z]

5

In [ ]:
#51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
#hint: dtype
x = np.zeros(10,[ ('position',[('x', float,1),
                              ('y',float,1)]),
                   ('color',[('r',float,1),
                            ('g',float,1),
                            ('b',float,1)] )])
x

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  import sys


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

In [ ]:
#52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
#(hint: np.atleast_2d, T, np.sqrt)
w = np.random.random((10,2))
x,y = np.atleast_2d(w[:,0],w[:,1])
d = np.sqrt((x-x.T)**2 + (y-y.T)**2)
d



array([[0.        , 0.45826219, 0.29049137, 0.67942538, 0.48600188,
        0.68462527, 0.35073883, 0.70995167, 0.42835253, 0.40998252],
       [0.45826219, 0.        , 0.51303659, 0.39597163, 0.37396972,
        0.32999654, 0.60316903, 0.4361129 , 0.42408205, 0.56688346],
       [0.29049137, 0.51303659, 0.        , 0.85341353, 0.70809889,
        0.58769623, 0.64119362, 0.55365419, 0.21132183, 0.12007156],
       [0.67942538, 0.39597163, 0.85341353, 0.        , 0.22936205,
        0.67157405, 0.59623371, 0.80341879, 0.81113808, 0.93272481],
       [0.48600188, 0.37396972, 0.70809889, 0.22936205, 0.        ,
        0.70112209, 0.36786421, 0.80951308, 0.71932916, 0.80552975],
       [0.68462527, 0.32999654, 0.58769623, 0.67157405, 0.70112209,
        0.        , 0.91305634, 0.14352233, 0.39535549, 0.57224372],
       [0.35073883, 0.60316903, 0.64119362, 0.59623371, 0.36786421,
        0.91305634, 0.        , 0.97954829, 0.75703298, 0.76042887],
       [0.70995167, 0.4361129 , 0.5536541

In [ ]:
#53. How to convert a float (32 bits) array into an integer (32 bits) in place?
#(hint: astype(copy=False))

x = np.random.rand(10).astype(np.float32)
y = x.view(np.int32)
y[:]= x
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [ ]:
import numpy as np
#55. What is the equivalent of enumerate for numpy arrays? (★★☆)
#(hint: np.ndenumerate, np.ndindex)
x = np.random.random((3,3))

for index in np.ndindex(x.shape):
  print(index,x[index])


(0, 0) 0.56608068913792
(0, 1) 0.44299235391063074
(0, 2) 0.8100427179064598
(1, 0) 0.5659507698046976
(1, 1) 0.0075629455509030885
(1, 2) 0.07316362807171628
(2, 0) 0.593543730982589
(2, 1) 0.5863602816407599
(2, 2) 0.07622559025642206


In [ ]:
#56. Generate a generic 2D Gaussian-like array (★★☆)
#(hint: np.meshgrid, np.exp)
x,y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
a = np.sqrt(x*x+y*y)
mu,sigma = 0.0,1.0
b = np.exp(-((a-mu)**2)/(2*sigma**2))
b



array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

In [ ]:
#57. How to randomly place p elements in a 2D array? (★★☆)
#(hint: np.put, np.random.choice)
n = 10
p =10
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),4)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 4. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 4. 0. 0.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 4. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 4. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [0. 4. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 4. 4. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#58. Subtract the mean of each row of a matrix 
#(hint: mean(axis=,keepdims=))
x = np.random.randn(5,5)
a = x-x.mean(axis =1,keepdims = True)
a

array([[ 1.05288852, -0.933179  , -0.09721557,  0.12618302, -0.14867697],
       [ 1.21997175, -1.22469786,  0.4775129 , -0.04076741, -0.43201938],
       [-0.15454772,  0.17070474,  0.30746488,  0.8346207 , -1.15824259],
       [ 0.41430878,  0.66149418, -1.43383367,  0.24969682,  0.10833389],
       [ 0.36582447,  0.55560446, -0.00360001,  0.54777847, -1.46560739]])

In [ ]:
#59. How to sort an array by the nth column? (★★☆)
#(hint: argsort)
x = np.random.randint(0,16,(4,4))
y = x[x[:,1].argsort()]
y


array([[ 6,  6, 15,  0],
       [13, 12,  1,  5],
       [ 9, 14,  0, 14],
       [ 4, 14, 15,  7]])

In [ ]:
#60. How to tell if a given 2D array has null columns? 
#(hint: any, ~)
x = np.random.randint(1,10,(5,5))
~x.any(axis = 0).any()

False

In [ ]:
#61. Find the nearest value from a given value in an array
#(hint: np.abs, argmin, flat)
x = np.random.uniform(0,1,3)
r = 0.3
z = x.flat[np.abs(x-r).argmin()]
print(z)

0.3471165498284585


In [ ]:
#62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
#(hint: np.nditer)
a = np.arange(1,3)
b = np.arange(3,1)

for i,j in np.nditer([a,b] ):
  print(sum(i,j))

In [ ]:

import numpy as np
#63. Create an array class that has a name attribute (★★☆)
#(hint: class method)
class Named(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = Named(np.arange(10), "science")
print (Z.name)

science


In [ ]:
#64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
#(hint: np.bincount | np.add.at)
x = np.ones(3)
y = np.random.randint(0,len(x),10)
x += np.bincount(y,minlength = len(x))
np.add.at(x,y,1)
print(x)



[3. 3. 1. 1. 3. 5. 5. 5. 3. 1.]


In [ ]:
X =[4,5,6,7,7,8]
Y = [1,2,3,4,5,6]
f= np.bincount(X,Y)
f

array([0., 0., 0., 0., 1., 2., 3., 9., 6.])

In [ ]:
#69. How to get the diagonal of a dot product? (★★★)
#hint: np.diag
x = np.random.randint(0,5,(3,3))
y = np.random.randint(0,5,(3,3))
z = np.diag(np.dot(x,y))
z


array([ 6, 14, 19])

In [ ]:
#83. How to find the most frequent value in an array?
#hint: np.bincount, argmax
x = np.array([2,22,2,2,2,3,4,4,4,4,5,6,7,8,9])
print(np.bincount(x).argmax())

2


In [ ]:
#89. How to get the n largest values of an array (★★★)
#(hint: np.argsort | np.argpartition)#

x = np.arange(200)
np.random.shuffle(x)
n = 3
print(x[np.argpartition(-x,n)[:n]])

[198 199 197]


In [ ]:
#72. How to swap two rows of an array? (★★★)
#(hint: array[[]] = array[[]])
x = np.arange(25).reshape(5,5)
x[[0,1]] == x[[1,0]]
x



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
#74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
#(hint: np.repeat)
C = np.bincount([1,2,3,4,5,6,1,1])
A = np.repeat(np.arange(len(C)),C)
print(A)

[1 1 1 2 3 4 5 6]


In [ ]:
#75. How to compute averages using a sliding window over an array? (★★★)
#(hint: np.cumsum)



In [ ]:
#77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
#hint: np.logical_not, np.negative#
x = np.arange(0,2,100)
np.logical_not(x,out = x)
print(x)
y= np.arange(-1,1,100)
np.negative(y,out = y)
print(y)


[1]
[1]


In [ ]:
#83. How to find the most frequent value in an array?
#hint: np.bincount, argmax

x = np.random.randint(0,10,15)


1
